forge 'https://forgeapi.puppetlabs.com'

# Module for access to NSIDC Enterprise storage
mod 'nsidc/nsidc_nfs',
  :git => 'git@bitbucket.org:/nsidc/puppet-nsidc-nfs.git',
  :ref => 'latest'

# This version is from March 2nd, 2015. Waiting for the authors to release the next version.
mod 'example42-php',
  :git => 'https://github.com/example42/puppet-php.git',
  :ref => 'f5ceb0a5c4ced7f890b7c16a4727f22a2864d920'

# Module for creating NSIDC Jenkins servers
mod 'nsidc/nsidc_jenkins',
  :git => 'git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git',
  :ref => 'latest'

# Module for installing python and pip.
# You may want to use this if using python's bumpversion
# for doing your version bumping.
# mod 'stankevich/python'
